# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
header = """# Changelog

All notable changes to this project will be documented in this file.

"""
body = """{% if version %}## {{ version | trim_start_matches(pat="v") }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}## Unreleased{% endif %}{% if previous %}{% if previous.commit_id and commit_id %}
[{{ previous.commit_id | truncate(length=7, end="") }}]({{ previous.commit_id }})...[{{ commit_id | truncate(length=7, end="") }}]({{ commit_id }}){% endif %}{% endif %}

### 🚨 BREAKING CHANGES

{% for c in commits %}{% if c.breaking %}{% set msg = c.message | split(pat="\n") | first | trim | upper_first %}- {{ msg }} ([{{ c.id | truncate(length=7, end="") }}]({{ c.id }})) - ({{ c.author.name }})
{% endif %}{% else %}- N/A{% endfor %}

{% for group, clist in commits | group_by(attribute="group") %}{% if group == "A Features" %}### 🚀 Features

{% for c in clist %}{% if not c.breaking %}{% set msg = c.message | split(pat="\n") | first | trim | upper_first %}- {{ msg }} ([{{ c.id | truncate(length=7, end="") }}]({{ c.id }})) - ({{ c.author.name }})
{% endif %}{% endfor %}{% endif %}{% endfor %}
{% for group, clist in commits | group_by(attribute="group") %}{% if group == "B Bug Fixes" %}### 🐛 Bug Fixes

{% for c in clist %}{% if not c.breaking %}{% set msg = c.message | split(pat="\n") | first | trim | upper_first %}- {{ msg }} ([{{ c.id | truncate(length=7, end="") }}]({{ c.id }})) - ({{ c.author.name }})
{% endif %}{% endfor %}{% endif %}{% endfor %}
{% for group, clist in commits | group_by(attribute="group") %}{% if group == "C Security" %}### 🔒 Security

{% for c in clist %}{% if not c.breaking %}{% set msg = c.message | split(pat="\n") | first | trim | upper_first %}- {{ msg }} ([{{ c.id | truncate(length=7, end="") }}]({{ c.id }})) - ({{ c.author.name }})
{% endif %}{% endfor %}{% endif %}{% endfor %}
{% for group, clist in commits | group_by(attribute="group") %}{% if group == "D Performance" %}### ⚡ Performance

{% for c in clist %}{% if not c.breaking %}{% set msg = c.message | split(pat="\n") | first | trim | upper_first %}- {{ msg }} ([{{ c.id | truncate(length=7, end="") }}]({{ c.id }})) - ({{ c.author.name }})
{% endif %}{% endfor %}{% endif %}{% endfor %}
{% for group, clist in commits | group_by(attribute="group") %}{% if group == "E Refactor" %}### ♻️ Refactor

{% for c in clist %}{% if not c.breaking %}{% set msg = c.message | split(pat="\n") | first | trim | upper_first %}- {{ msg }} ([{{ c.id | truncate(length=7, end="") }}]({{ c.id }})) - ({{ c.author.name }})
{% endif %}{% endfor %}{% endif %}{% endfor %}
{% for group, clist in commits | group_by(attribute="group") %}{% if group == "F Testing" %}### ✅ Testing

{% for c in clist %}{% if not c.breaking %}{% set msg = c.message | split(pat="\n") | first | trim | upper_first %}- {{ msg }} ([{{ c.id | truncate(length=7, end="") }}]({{ c.id }})) - ({{ c.author.name }})
{% endif %}{% endfor %}{% endif %}{% endfor %}
{% for group, clist in commits | group_by(attribute="group") %}{% if group == "G Styling" %}### 💄 Styling

{% for c in clist %}{% if not c.breaking %}{% set msg = c.message | split(pat="\n") | first | trim | upper_first %}- {{ msg }} ([{{ c.id | truncate(length=7, end="") }}]({{ c.id }})) - ({{ c.author.name }})
{% endif %}{% endfor %}{% endif %}{% endfor %}
{% for group, clist in commits | group_by(attribute="group") %}{% if group == "H Build" %}### 🔨 Build

{% for c in clist %}{% if not c.breaking %}{% set msg = c.message | split(pat="\n") | first | trim | upper_first %}- {{ msg }} ([{{ c.id | truncate(length=7, end="") }}]({{ c.id }})) - ({{ c.author.name }})
{% endif %}{% endfor %}{% endif %}{% endfor %}
{% for group, clist in commits | group_by(attribute="group") %}{% if group == "I Documentation" %}### 📖 Documentation

{% for c in clist %}{% if not c.breaking %}{% set msg = c.message | split(pat="\n") | first | trim | upper_first %}- {{ msg }} ([{{ c.id | truncate(length=7, end="") }}]({{ c.id }})) - ({{ c.author.name }})
{% endif %}{% endfor %}{% endif %}{% endfor %}
{% for group, clist in commits | group_by(attribute="group") %}{% if group == "Z Miscellaneous Tasks" %}### 🔧 Miscellaneous Tasks

{% for c in clist %}{% if not c.breaking %}{% set msg = c.message | split(pat="\n") | first | trim | upper_first %}- {{ msg }} ([{{ c.id | truncate(length=7, end="") }}]({{ c.id }})) - ({{ c.author.name }})
{% endif %}{% endfor %}{% endif %}{% endfor %}

"""
footer = """<!-- generated by git-cliff -->"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
protect_breaking_commits = true
commit_parsers = [
    { message = "^feat", group = "A Features" },
    { message = "^fix", group = "B Bug Fixes" },
    { message = "^security", group = "C Security" },
    { message = "^perf", group = "D Performance" },
    { message = "^refactor", group = "E Refactor" },
    { message = "^test", group = "F Testing" },
    { message = "^style", group = "G Styling" },
    { message = "^build", group = "H Build" },
    { message = "^doc", group = "I Documentation" },
    { message = "^chore|^ci", group = "Z Miscellaneous Tasks" },
    { body = ".*security", group = "C Security" },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^chore\\(release\\): prepare for", skip = true },
]
filter_commits = false
topo_order = false
sort_commits = "oldest"
