/**
 * @fileoverview ZTM Chat Connectivity Types
 * @module types/connectivity
 * Types for ZTM mesh connectivity and permit data
 */

/**
 * @description ZTM Permit Data Structure
 *
 * This data structure is returned by the permit server and contains
 * all necessary information to join a ZTM mesh.
 *
 * CA (ca field): The Certificate Authority certificate of the mesh.
 * This is generated by the ZTM Hub when it's first started and is
 * distributed to all endpoints via the permit.
 */
export interface PermitData {
  /** CA certificate in PEM format */
  ca: string;

  /** Agent-specific data */
  agent: {
    /** Agent certificate in PEM format (issued by CA) */
    certificate: string;

    /** Private key in PEM format (generated locally, returned by permit server) */
    privateKey?: string;

    /** Optional labels for the endpoint */
    labels?: string[];
  };

  /** Array of bootstrap hub addresses (host:port) */
  bootstraps: string[];
}
